version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "{{LAMBDA_FUNCTION_NAME}}"
        Alias: "{{LAMBDA_ALIAS}}"
        CurrentVersion: "{{CURRENT_LAMBDA_VERSION}}"
        TargetVersion: "{{TARGET_LAMBDA_VERSION}}"
Hooks:
  - BeforeAllowTraffic: "{{BEFORE_ALLOW_TRAFFIC_HOOK}}"
  - AfterAllowTraffic: "{{AFTER_ALLOW_TRAFFIC_HOOK}}"