version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "myHelloWorldLambda"
        Alias: "hello-world-alias"
        CurrentVersion: "9"
        TargetVersion: "10"
Hooks:
  - BeforeAllowTraffic: "myHelloWorldLambda-BeforeAllowTraffic"
  - AfterAllowTraffic: "myHelloWorldLambda-AfterAllowTraffic"